name: SonarCloud Analysis

on:
  push:
    branches:
      - main   # Change this to your default branch or target branch
  pull_request:
    branches:
      - main   # Runs for pull requests targeting the main branch

jobs:
  sonarcloud:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Replace with your Python version (e.g., 3.8, 3.9, etc.)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage

    - name: Run tests with coverage
      run: |
        # Run tests and generate coverage report
        coverage run -m pytest
        coverage report  # Display coverage summary in the logs
        coverage xml -o coverage.xml  # Generate a coverage.xml file for SonarCloud analysis

    - name: Run SonarCloud analysis
      uses: SonarSource/sonarcloud-github-action@v1
      with:
        organization: your-sonarcloud-organization  # Replace with your SonarCloud organization name
        projectKey: your-sonarcloud-project-key  # Replace with your SonarCloud project key
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # GitHub secret containing your SonarCloud token
